import type {
  Patient,
  Provider,
  Medication,
  DrugInteraction,
  Visit,
  Condition,
  LabPanel,
  CompleteHealthRecord,
} from '../domain/types';

const providers: Record<string, Provider> = {
  torres: { id: 'p1', name: 'Dr. Michael Torres', facility: 'Bayside Medical Group', type: 'Primary Care' },
  okafor: { id: 'p2', name: 'Dr. James Okafor', facility: 'Bay Area Cardiology', type: 'Specialist' },
  chen: { id: 'p3', name: 'Dr. Sarah Chen', facility: 'Bay Dermatology', type: 'Specialist' },
  park: { id: 'p4', name: 'Dr. Emily Park', facility: 'Bay Area Orthopedics', type: 'Specialist' },
  patel: { id: 'p5', name: 'Dr. Priya Patel', facility: 'CityHealth Urgent Care', type: 'Urgent Care' },
  nguyen: { id: 'p6', name: 'Dr. Amy Nguyen', facility: 'CityHealth Urgent Care', type: 'Urgent Care' },
};

const patient: Patient = {
  id: 'u1',
  firstName: 'Sam',
  lastName: 'Johnson',
  dateOfBirth: 'June 14, 1991',
  bloodType: 'O+',
  primaryCareProvider: providers.torres,
  allergies: ['Sulfa drugs', 'Shellfish'],
  emergencyContact: {
    name: 'Sam Johnson',
    phone: '(555) 867-5309',
    relationship: 'Spouse',
  },
};

const conditions: Condition[] = [
  {
    id: 'c1',
    name: 'Stage 1 Hypertension',
    diagnosedDate: 'Sep 8, 2025',
    management: 'Managed with Lisinopril 10mg daily. Blood pressure currently averaging 128/82 with medication.',
    provider: providers.okafor,
    status: 'active',
  },
  {
    id: 'c2',
    name: 'Elevated LDL Cholesterol',
    diagnosedDate: 'Jan 15, 2026',
    management: 'LDL 142 mg/dL. Currently managed with diet and exercise changes. Medication may be considered if not improved by July 2026.',
    provider: providers.torres,
    status: 'active',
  },
  {
    id: 'c3',
    name: 'Seasonal Allergic Rhinitis',
    diagnosedDate: 'Aug 20, 2025',
    management: 'Managed with Cetirizine 10mg daily and Flonase as needed. Symptoms worst in spring/summer.',
    provider: providers.torres,
    status: 'active',
  },
  {
    id: 'c4',
    name: 'Pending: Mole Biopsy Results',
    diagnosedDate: 'Feb 12, 2026',
    management: 'Irregular mole on upper back biopsied by Dr. Sarah Chen. Results pending. Follow-up March 14, 2026.',
    provider: providers.chen,
    status: 'pending',
  },
  {
    id: 'c5',
    name: 'Acute Bronchitis',
    diagnosedDate: 'Oct 18, 2025',
    resolvedDate: 'Nov 2025',
    management: 'Treated with Azithromycin. Post-infectious cough lingered ~5 weeks total but fully resolved.',
    provider: providers.nguyen,
    status: 'resolved',
  },
  {
    id: 'c6',
    name: 'Strep Throat',
    diagnosedDate: 'May 22, 2025',
    resolvedDate: 'Jun 2025',
    management: 'Treated with 10-day course of Amoxicillin. Full recovery.',
    provider: providers.torres,
    status: 'resolved',
  },
  {
    id: 'c7',
    name: 'Lower Back Strain',
    diagnosedDate: 'Jul 10, 2025',
    resolvedDate: 'Sep 2025',
    management: 'Treated with physical therapy (12 sessions) and short-term muscle relaxant. Pain fully resolved after 8 weeks.',
    provider: providers.park,
    status: 'resolved',
  },
];

const medications: Medication[] = [
  {
    id: 'm1',
    name: 'Lisinopril 10mg',
    dosage: '1 tablet daily, in the morning',
    instructions: 'May cause dry cough. Stand up slowly to avoid dizziness.',
    purpose: 'Blood pressure (ACE inhibitor)',
    prescribedBy: providers.okafor,
    startDate: 'September 8, 2025',
    status: 'active-ongoing',
  },
  {
    id: 'm2',
    name: 'Cetirizine (Zyrtec) 10mg',
    dosage: '1 tablet daily',
    instructions: 'May cause drowsiness in some people.',
    purpose: 'Seasonal allergies (antihistamine)',
    prescribedBy: providers.torres,
    startDate: 'August 20, 2025',
    status: 'active-ongoing',
  },
  {
    id: 'm3',
    name: 'Fluticasone Nasal Spray (Flonase)',
    dosage: '2 sprays each nostril, daily as needed',
    instructions: 'Use regularly during allergy season for best results.',
    purpose: 'Nasal congestion and allergy symptoms',
    prescribedBy: providers.torres,
    startDate: 'August 20, 2025',
    status: 'active-as-needed',
  },
  {
    id: 'm4',
    name: 'Ibuprofen 600mg',
    dosage: '3 times daily with food',
    instructions: 'Always take with food to prevent stomach issues. Do not exceed prescribed dose.',
    purpose: 'Knee pain and inflammation (NSAID)',
    prescribedBy: providers.patel,
    startDate: 'February 28, 2026',
    duration: '2 weeks (until ~March 14)',
    status: 'active-short-term',
  },
  {
    id: 'm5',
    name: 'Vitamin D3 2000 IU',
    dosage: '1 daily',
    instructions: 'January bloodwork showed Vitamin D at 24 ng/mL (optimal is 30+). Recheck at next blood panel.',
    purpose: 'Vitamin D supplementation',
    prescribedBy: providers.torres,
    startDate: 'January 15, 2026',
    status: 'active-ongoing',
  },
  {
    id: 'm6',
    name: 'Dextromethorphan (OTC)',
    dosage: 'As needed at bedtime',
    instructions: 'For lingering post-infectious cough. Use only if cough interferes with sleep.',
    purpose: 'Cough suppression',
    prescribedBy: providers.torres,
    startDate: 'November 3, 2025',
    status: 'active-as-needed',
  },
  {
    id: 'm7',
    name: 'Azithromycin (Z-Pack)',
    dosage: '500mg day 1, 250mg days 2-5',
    instructions: '',
    purpose: 'Bronchitis (antibiotic)',
    prescribedBy: providers.nguyen,
    startDate: 'October 18, 2025',
    endDate: 'October 22, 2025',
    status: 'completed',
  },
  {
    id: 'm8',
    name: 'Amoxicillin 500mg',
    dosage: '3 times daily for 10 days',
    instructions: '',
    purpose: 'Strep throat (antibiotic)',
    prescribedBy: providers.torres,
    startDate: 'May 22, 2025',
    endDate: 'June 1, 2025',
    status: 'completed',
  },
  {
    id: 'm9',
    name: 'Cyclobenzaprine 10mg',
    dosage: '1 at bedtime for 2 weeks',
    instructions: '',
    purpose: 'Back pain muscle relaxant',
    prescribedBy: providers.park,
    startDate: 'July 10, 2025',
    endDate: 'July 24, 2025',
    status: 'completed',
  },
];

const interactions: DrugInteraction[] = [
  {
    id: 'i1',
    medication1Id: 'm4',
    medication2Id: 'm1',
    description: 'Ibuprofen and other NSAIDs can reduce the blood-pressure-lowering effect of ACE inhibitors like Lisinopril. Taking both regularly can also increase the risk of kidney problems, especially with prolonged use.',
    severity: 'moderate',
    dateFlagged: 'February 28, 2026',
    actionRequired: 'Talk to your doctor before continuing both medications. Consider using Acetaminophen (Tylenol) instead of Ibuprofen for pain relief, as it doesn\'t interact with Lisinopril.',
  },
];

const visits: Visit[] = [
  {
    id: 'v1',
    date: 'February 28, 2026',
    durationMinutes: 18,
    type: 'Urgent Care',
    provider: providers.patel,
    reason: 'Right knee pain after running',
    summary: "You went to urgent care for pain in your right knee after a long run over the weekend. Dr. Patel examined your knee and found some swelling on the outside of the kneecap. She doesn't think anything is torn but ordered an X-ray to rule out a stress fracture. Results should be back in 2-3 days. She prescribed Ibuprofen 600mg to take 3 times daily with food for the pain and swelling. She said to ice it for 20 minutes at a time, stay off running for at least 2 weeks, and come back if the pain gets worse or doesn't improve in 10 days.",
    medicationsPrescribed: [medications.find(m => m.id === 'm4')!],
    followUpActions: [
      'X-ray results in 2-3 days (expect a call)',
      'Return visit if pain worsens or persists beyond 10 days',
      'No running for 2 weeks minimum',
      'Ice 20 minutes, 3-4 times daily',
    ],
    transcript: [
      { speaker: 'Dr. Patel', text: 'So tell me what happened with your knee.' },
      { speaker: 'Sam', text: "I went for a run on Saturday, about 8 miles, and by the end my right knee was really hurting. It's been sore ever since." },
      { speaker: 'Dr. Patel', text: 'And where exactly is the pain?' },
      { speaker: 'Sam', text: 'On the outside, kind of below the kneecap.' },
      { speaker: 'Dr. Patel', text: "OK. I'm going to press around here — tell me if this hurts... I can feel some swelling around the lateral aspect of the patella. Range of motion looks fine though. I don't think we're dealing with a ligament tear, but I'd like to get an X-ray to rule out a stress fracture since you said you recently increased your mileage." },
      { speaker: 'Sam', text: 'Sure, that makes sense.' },
      { speaker: 'Dr. Patel', text: "In the meantime, I'm going to prescribe you ibuprofen 600 milligrams. Take it three times a day with food. That should help with both the pain and the inflammation. And I want you to ice it — 20 minutes on, 20 minutes off — a few times a day. No running for at least two weeks." },
      { speaker: 'Sam', text: 'OK, got it. When will I hear about the X-ray?' },
      { speaker: 'Dr. Patel', text: "We should have results within two to three business days. We'll call you. If things get worse before then or you're not feeling better after about ten days, come back and we'll take another look." },
    ],
  },
  {
    id: 'v2',
    date: 'February 12, 2026',
    durationMinutes: 22,
    type: 'Specialist',
    provider: providers.chen,
    reason: 'Annual skin check',
    summary: "You had your annual full-body skin check with Dr. Chen. She examined all your moles and freckles. Most everything looked normal, but she found one mole on your upper back that had irregular borders and uneven coloring. She performed a shave biopsy right there in the office — she numbed the area first, removed a thin layer of the mole, and sent it to the lab. She said it's probably nothing but she wants to be sure. Results should come back in 7-10 days. She also recommended using SPF 50 sunscreen daily, even in winter, because of your fair skin. Follow-up appointment booked for March 14 to discuss biopsy results.",
    medicationsPrescribed: [],
    followUpActions: [
      'Biopsy results in 7-10 days',
      'Follow-up appointment: March 14, 2026',
      'Start daily SPF 50 sunscreen',
    ],
    transcript: [],
  },
  {
    id: 'v3',
    date: 'January 15, 2026',
    durationMinutes: 34,
    type: 'Primary Care',
    provider: providers.torres,
    reason: 'Annual physical exam',
    summary: "Annual physical with Dr. Torres. Vitals all looked good — blood pressure was 128/82, which he said is slightly elevated but not concerning yet since you're on Lisinopril. Weight was 181 lbs, up 4 lbs from last year. He ordered a full blood panel including cholesterol, blood sugar, thyroid, and kidney function. Results came back a few days later: your LDL cholesterol was 142 mg/dL, which is a bit above the ideal range of under 130. He said your blood sugar and thyroid levels were normal. He recommended reducing red meat and fried food, adding more fish and vegetables, and getting 30 minutes of cardio 4-5 times a week. He wants to recheck cholesterol in 6 months before considering medication. Your Vitamin D level was also a bit low at 24 ng/mL, so he started you on Vitamin D3 2000 IU daily. He also renewed your Lisinopril and Cetirizine prescriptions.",
    medicationsPrescribed: [
      medications.find(m => m.id === 'm1')!,
      medications.find(m => m.id === 'm2')!,
      medications.find(m => m.id === 'm5')!,
    ],
    followUpActions: [
      'Cholesterol recheck in 6 months (July 2026)',
      'Dietary changes: reduce red meat, increase fish and vegetables',
      'Exercise: 30 min cardio, 4-5 times per week',
    ],
    transcript: [],
  },
  {
    id: 'v4',
    date: 'November 3, 2025',
    durationMinutes: 15,
    type: 'Telehealth',
    provider: providers.torres,
    reason: 'Persistent cough follow-up',
    summary: "Telehealth follow-up about a cough that had been lasting 3 weeks. Dr. Torres reviewed your chart and noted you'd been seen for this cough at urgent care 2 weeks ago and were given a Z-pack (azithromycin). The cough has improved but not gone away completely. He said this is normal — post-infectious cough can linger for 4-6 weeks after a respiratory infection. He recommended continuing with honey and tea, using a humidifier at night, and trying over-the-counter Dextromethorphan cough suppressant at bedtime if the cough keeps you up. He said if it's not gone in another 3 weeks, he'd want to do a chest X-ray.",
    medicationsPrescribed: [medications.find(m => m.id === 'm6')!],
    followUpActions: [
      'Return if cough persists beyond 6 weeks total',
      'Chest X-ray if no improvement',
    ],
    transcript: [],
  },
  {
    id: 'v5',
    date: 'October 18, 2025',
    durationMinutes: 12,
    type: 'Urgent Care',
    provider: providers.nguyen,
    reason: 'Persistent cough, 1 week',
    summary: "You went to urgent care for a cough that started a week ago and was getting worse. Dr. Nguyen listened to your lungs and said they sounded clear, so she didn't think it was pneumonia. She checked your oxygen levels (97%, normal) and took a rapid strep test (negative) and COVID test (negative). She diagnosed you with acute bronchitis — basically a chest cold. She prescribed Azithromycin (Z-pack) — 500mg the first day, then 250mg daily for 4 more days. She said to drink lots of fluids, rest, and take Tylenol if you develop a fever.",
    medicationsPrescribed: [medications.find(m => m.id === 'm7')!],
    followUpActions: [
      'Follow up with primary care if not improving in 2 weeks',
    ],
    transcript: [],
  },
  {
    id: 'v6',
    date: 'September 8, 2025',
    durationMinutes: 28,
    type: 'Specialist',
    provider: providers.okafor,
    reason: 'Blood pressure medication review',
    summary: "First visit with Dr. Okafor, a cardiologist. Dr. Torres referred you after your blood pressure was consistently reading above 130/85 at your last few primary care visits. Dr. Okafor took your blood pressure in the office (136/87) and reviewed your home blood pressure logs (you'd been tracking at home for 2 months). He confirmed you have Stage 1 hypertension. He started you on Lisinopril 10mg, once daily in the morning. He explained it's an ACE inhibitor that helps relax blood vessels. He said common side effects include a dry cough and dizziness when standing up quickly. He wants you to keep logging your blood pressure at home and come back in 6 months for a check-in. He also recommended reducing salt intake and aiming for less than 2,300mg sodium per day.",
    medicationsPrescribed: [{ ...medications.find(m => m.id === 'm1')!, status: 'active-ongoing', startDate: 'September 8, 2025' }], // Simplified for history view
    followUpActions: [
      'Continue home blood pressure monitoring',
      'Reduce sodium to <2,300mg daily',
      '6-month follow-up: March 10, 2026',
    ],
    transcript: [],
  },
  {
    id: 'v7',
    date: 'August 20, 2025',
    durationMinutes: 20,
    type: 'Primary Care',
    provider: providers.torres,
    reason: 'Allergies and blood pressure follow-up',
    summary: "You went in because your seasonal allergies were really bad this year — sneezing, itchy eyes, congestion. Dr. Torres prescribed Cetirizine (Zyrtec) 10mg daily and recommended Flonase nasal spray as needed. He also rechecked your blood pressure which was 134/86. He said it's still borderline high and referred you to a cardiologist, Dr. James Okafor, for evaluation. He said it may be time to start a low-dose blood pressure medication.",
    medicationsPrescribed: [
      { ...medications.find(m => m.id === 'm2')! },
      { ...medications.find(m => m.id === 'm3')! },
    ],
    followUpActions: [
      'Cardiology referral: Dr. James Okafor',
      'Blood pressure monitoring at home',
    ],
    transcript: [],
  },
  {
    id: 'v8',
    date: 'July 10, 2025',
    durationMinutes: 25,
    type: 'Specialist',
    provider: providers.park,
    reason: 'Lower back pain evaluation',
    summary: "You saw Dr. Park for lower back pain that started about 6 weeks ago after helping a friend move furniture. The pain is in your lower left side, worse when sitting for long periods. She did a physical exam — range of motion was limited but no nerve involvement (leg strength and reflexes were normal). She said it's likely a muscle strain that's been slow to heal because you sit at a desk all day. She recommended physical therapy — 2 sessions per week for 6 weeks. She also prescribed Cyclobenzaprine (a muscle relaxant) to take at bedtime for 2 weeks to help with sleep since the pain was waking you up. She said if there's no improvement after 6 weeks of PT, she'd want to do an MRI.",
    medicationsPrescribed: [medications.find(m => m.id === 'm9')!],
    followUpActions: [
      'Physical therapy: 2x/week for 6 weeks',
      'Follow up if no improvement after PT',
      'Ergonomic desk setup recommended',
    ],
    transcript: [],
  },
  {
    id: 'v9',
    date: 'May 22, 2025',
    durationMinutes: 16,
    type: 'Primary Care',
    provider: providers.torres,
    reason: 'Sore throat and fatigue',
    summary: "You came in feeling run down with a sore throat for 3 days. Dr. Torres did a rapid strep test which came back positive. He prescribed Amoxicillin 500mg, 3 times daily for 10 days. He said you should start feeling better within 48 hours but need to finish the full course. He recommended throat lozenges and warm salt water gargling for comfort. He also advised staying home from work for at least 24 hours after starting the antibiotic.",
    medicationsPrescribed: [medications.find(m => m.id === 'm8')!],
    followUpActions: [
      'Complete full 10-day antibiotic course',
      'Return if symptoms worsen or don\'t improve in 48 hours',
    ],
    transcript: [],
  },
  {
    id: 'v10',
    date: 'March 5, 2025',
    durationMinutes: 30,
    type: 'Primary Care',
    provider: providers.torres,
    reason: 'New patient visit / initial physical',
    summary: "This was your first visit with Dr. Torres after moving to the area. He did a full physical exam and took your medical history. Blood pressure was 130/84, which he noted is borderline. Weight 177 lbs. He said everything looked good. He ordered baseline bloodwork — results came back normal across the board (cholesterol was 128 LDL, within range at that time). He wants to see you annually for physicals and said to keep an eye on blood pressure. He asked about family history — you mentioned your father has high blood pressure and your mother had high cholesterol, so he flagged both as things to monitor.",
    medicationsPrescribed: [],
    followUpActions: [
      'Annual physical — schedule for early next year',
      'Monitor blood pressure at home',
      'Family history noted: father — hypertension, mother — hypercholesterolemia',
    ],
    transcript: [],
  },
];

const labPanels: LabPanel[] = [
  {
    id: 'l1',
    name: 'Blood Panel',
    dateDrawn: 'January 15, 2026',
    orderedBy: providers.torres,
    results: [
      { id: 'lr1', name: 'LDL Cholesterol', value: 142, unit: 'mg/dL', referenceRange: '<130', status: 'high' },
      { id: 'lr2', name: 'HDL Cholesterol', value: 52, unit: 'mg/dL', referenceRange: '>40', status: 'normal' },
      { id: 'lr3', name: 'Total Cholesterol', value: 218, unit: 'mg/dL', referenceRange: '<200', status: 'borderline' },
      { id: 'lr4', name: 'Triglycerides', value: 120, unit: 'mg/dL', referenceRange: '<150', status: 'normal' },
      { id: 'lr5', name: 'Fasting Glucose', value: 94, unit: 'mg/dL', referenceRange: '<100', status: 'normal' },
      { id: 'lr6', name: 'TSH (Thyroid)', value: 2.1, unit: 'mIU/L', referenceRange: '0.4-4.0', status: 'normal' },
      { id: 'lr7', name: 'Creatinine', value: 1.0, unit: 'mg/dL', referenceRange: '0.7-1.3', status: 'normal' },
      { id: 'lr8', name: 'Vitamin D', value: 24, unit: 'ng/mL', referenceRange: '30-100', status: 'low' },
    ]
  },
  {
    id: 'l2',
    name: 'Blood Panel',
    dateDrawn: 'March 10, 2025',
    orderedBy: providers.torres,
    results: [
      { id: 'lr1b', name: 'LDL Cholesterol', value: 128, unit: 'mg/dL', referenceRange: '<130', status: 'normal' },
      { id: 'lr2b', name: 'HDL Cholesterol', value: 55, unit: 'mg/dL', referenceRange: '>40', status: 'normal' },
      { id: 'lr3b', name: 'Total Cholesterol', value: 198, unit: 'mg/dL', referenceRange: '<200', status: 'normal' },
      { id: 'lr5b', name: 'Fasting Glucose', value: 89, unit: 'mg/dL', referenceRange: '<100', status: 'normal' },
    ]
  }
];

export const MOCK_DATA: CompleteHealthRecord = {
  patient,
  visits,
  medications,
  conditions,
  labPanels,
  interactions,
};

// Simulate an API call
export const fetchHealthRecord = (): Promise<CompleteHealthRecord> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(MOCK_DATA);
    }, 500);
  });
};
